from pathlib import Path
from typing import Protocol


class Storage(Protocol):
    async def save(self, filename: str, content: bytes, category: str = "original") -> str: ...

    async def save_file(self, filename: str, source: Path, category: str = "original") -> str: ...

    async def delete(self, path: str) -> None: ...

    def resolve(self, path: str) -> Path: ...
